# Generated by Django 4.2.7 on 2023-11-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
